# Build numbering format
name: $(BuildID)

trigger:
  branches:
    include:
      - demo
  paths:
    include:
      - '*'
    exclude:
      - 'apps/admin/*'
      - 'apps/commerce/*'
      - 'apps/vendor/*'
      - 'libs/storybook/*'

resources:
  - repo: self

stages:
  - stage: Build
    displayName: Build image and deploy
    jobs:
      - job: Build
        displayName: Build
        pool:
          name: demo-frontend-194
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                docker-compose -f docker-compose-demo.yml build --no-cache demo-storybook
                docker-compose -f docker-compose-demo.yml build --no-cache demo-admin
                docker-compose -f docker-compose-demo.yml build --no-cache demo-vendor
                docker-compose -f docker-compose-demo.yml build --no-cache demo-commerce
                docker-compose -f docker-compose-demo.yml down
                docker-compose -f docker-compose-demo.yml up -d
              displayName: 'Build Whole Monorepo'
              workingDirectory: $(System.DefaultWorkingDirectory)
