FROM docker.hasti.co/node/hit-node-build as starter
WORKDIR /build
COPY . /build
#ENV http_proxy=http://172.27.226.11:10809
#ENV https_proxy=http://172.27.226.11:10809
#RUN npm config set http_proxy http://172.27.226.11:10809 && \
#    npm config set http_proxy http://172.27.226.11:10809 && \
#    npm config set http_proxy http://172.27.226.11:10809 && \
#    npm set strict-ssl false
    
RUN yarn
RUN yarn vendor-codegen
RUN yarn vendor-build
EXPOSE 4001
#ENV http_proxy=""
#ENV https_proxy=""

FROM docker.hasti.co/node/node:16-alpine
COPY --from=starter /build /build
WORKDIR /build
CMD yarn vendor --configuration=production --host 0.0.0.0
