FROM docker.hasti.co/node/hit-node-build as builder
WORKDIR /build
COPY . /build
#ENV http_proxy=http://172.27.226.11:10809
#ENV https_proxy=http://172.27.226.11:10809
#RUN npm config set http_proxy http://172.27.226.11:10809 && \
#    npm config set http_proxy http://172.27.226.11:10809 && \
#    npm config set http_proxy http://172.27.226.11:10809 && \
#    npm set strict-ssl false
RUN yarn
RUN yarn build-story

FROM docker.hasti.co/node/nginx:1.21-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
# COPY .htpassword /etc/nginx/.htpassword
COPY --from=builder /build/dist/storybook/storybook /usr/share/nginx/html


