export enum FormPatternsEnums {
  Integer = '^[0-9]*$',
  Date = '^[0-9]{4}-[0-9]{2}-[0-9]{2}$',
  EnText = '^[a-zA-Z0-9.-]*$',
  Email = '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}$',
  URL = '^(http|https)://[a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)+([a-zA-Z0-9-./?%&=]*)?$',
  Tel = '^[0-9]{8,}$',
  TelWithAreaCode = '^0[0-9]{2,}[0-9]{7,}$',
  Mobile = '^09(1[0-9]|3[1-9]|2[1-9])-?[0-9]{3}-?[0-9]{4}$',
  Decimal = '^[0-9]+(.[0-9]{1,2})?$',
  OneDecimal = '^[0-9]+(.[0-9]{1})?$',
  Color = '^#([0-9a-fA-F]{6}|[0-9a-fA-F]{3})$',
  Money = '^[0-9]+(.[0-9]{1,2})?$',
  NationalCode = '^[0-9]{10}$',
  PostalCode = '^[0-9]{10}$',
  Password = '^[a-zA-Z0-9]{8,}$',
  PersianText = '^[آ-ی]*$',
  PersianTextWithSpace = '^[آ-ی ]*$',
  PersianTextWithSpaceAndNumber = '^[آ-ی 0-9]*$',
  PersianTextWithSpaceAndNumberAndDash = '^[آ-ی 0-9-]*$',
  PersianTextWithSpaceAndNumberAndDashAndSlash = '^[آ-ی 0-9-/]*$',
  PersianTextWithSpaceAndNumberAndDashAndSlashAndDot = '^[آ-ی 0-9-/.]*$',
  Shaba = '^(?=.{24}$)[0-9]*$',
}
