export type HBContainerWithTreeClassnames =
  | 'toolsContainer'
  | 'mainContainer'
  | 'treeColumn'
  | 'treeItems'
  | 'container'
  | 'optionsColumn'
  | 'pageTitleBar'
  | 'dataNotFound'
  | 'displayAddChildrenButton'
  | 'bullet'
